"""empty message

Revision ID: a1e844932aa9
Revises: 
Create Date: 2020-01-15 15:24:27.841407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1e844932aa9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_meta',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('meta_key', sa.String(length=128), nullable=False),
    sa.Column('meta_value', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('page',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('page_title', sa.String(length=128), nullable=False),
    sa.Column('page_name', sa.String(length=256), nullable=False),
    sa.Column('page_active', sa.Boolean(), nullable=True),
    sa.Column('page_author', sa.String(length=128), nullable=True),
    sa.Column('page_date', sa.DateTime(), nullable=True),
    sa.Column('page_content', sa.String(length=30000), nullable=True),
    sa.Column('page_status', sa.String(length=32), nullable=False),
    sa.Column('page_parent', sa.Integer(), nullable=True),
    sa.Column('page_guid', sa.String(length=256), nullable=False),
    sa.Column('page_cached', sa.Boolean(), nullable=True),
    sa.Column('page_do_not_cache', sa.Boolean(), nullable=True),
    sa.Column('page_cached_date', sa.DateTime(), nullable=True),
    sa.Column('page_cached_content', sa.String(length=30000), nullable=True),
    sa.Column('page_do_not_import', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['page_parent'], ['page.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('page_name')
    )
    op.create_table('photo_gallery',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('old_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('slug_name', sa.String(length=256), nullable=False),
    sa.Column('path_name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=256), nullable=False),
    sa.Column('email', sa.String(length=40), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('website', sa.String(length=60), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('email_confirmed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_name', sa.String(length=128), nullable=False),
    sa.Column('event_description', sa.String(length=1024), nullable=True),
    sa.Column('event_location', sa.Integer(), nullable=True),
    sa.Column('event_cost', sa.String(length=128), nullable=True),
    sa.Column('event_sign_up', sa.String(length=128), nullable=True),
    sa.Column('event_EC_pickup', sa.String(length=128), nullable=True),
    sa.Column('event_HL_pick_up', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['event_location'], ['event_meta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('page_meta',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('meta_key', sa.String(length=128), nullable=False),
    sa.Column('meta_value', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['page.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('old_id', sa.Integer(), nullable=False),
    sa.Column('image_slug', sa.String(length=256), nullable=False),
    sa.Column('gallery_id', sa.Integer(), nullable=True),
    sa.Column('old_gallery_id', sa.Integer(), nullable=True),
    sa.Column('file_name', sa.String(length=256), nullable=True),
    sa.Column('caption', sa.String(length=512), nullable=True),
    sa.Column('alt_text', sa.String(length=256), nullable=True),
    sa.Column('image_date', sa.DateTime(), nullable=True),
    sa.Column('meta_data', sa.UnicodeText(), nullable=True),
    sa.ForeignKeyConstraint(['gallery_id'], ['photo_gallery.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photo_gallery_meta',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gallery_id', sa.Integer(), nullable=False),
    sa.Column('meta_key', sa.String(length=128), nullable=False),
    sa.Column('meta_value', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['gallery_id'], ['photo_gallery.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photo_meta',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gallery_id', sa.Integer(), nullable=False),
    sa.Column('meta_key', sa.String(length=128), nullable=False),
    sa.Column('meta_value', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['gallery_id'], ['photo_gallery.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_meta_tbl',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('meta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meta_id'], ['event_meta.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', 'meta_id')
    )
    op.create_table('event_time',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('all_day_event', sa.Boolean(), nullable=True),
    sa.Column('start', sa.DateTime(), nullable=True),
    sa.Column('end', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_time')
    op.drop_table('event_meta_tbl')
    op.drop_table('user_roles')
    op.drop_table('photo_meta')
    op.drop_table('photo_gallery_meta')
    op.drop_table('photo')
    op.drop_table('page_meta')
    op.drop_table('event')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('photo_gallery')
    op.drop_table('page')
    op.drop_table('event_meta')
    # ### end Alembic commands ###
