"""empty message

Revision ID: dbca8c1fced9
Revises: 
Create Date: 2020-01-14 15:32:28.102430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbca8c1fced9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('page_title', sa.String(length=1024), nullable=False),
    sa.Column('page_name', sa.String(length=255), nullable=False),
    sa.Column('page_active', sa.Boolean(), nullable=True),
    sa.Column('page_author', sa.String(length=128), nullable=True),
    sa.Column('page_date', sa.DateTime(), nullable=True),
    sa.Column('page_content', sa.String(length=30000), nullable=True),
    sa.Column('page_status', sa.String(length=32), nullable=False),
    sa.Column('page_parent', sa.Integer(), nullable=True),
    sa.Column('page_guid', sa.String(length=255), nullable=False),
    sa.Column('page_cached', sa.Boolean(), nullable=True),
    sa.Column('page_do_not_cache', sa.Boolean(), nullable=True),
    sa.Column('page_cached_date', sa.DateTime(), nullable=True),
    sa.Column('page_cached_content', sa.String(length=30000), nullable=True),
    sa.Column('page_do_not_import', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['page_parent'], ['page.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('page_name')
    )
    op.create_table('photo_gallery',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('old_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug_name', sa.String(length=255), nullable=False),
    sa.Column('path_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('website', sa.String(length=80), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('email_confirmed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('page_meta',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('meta_key', sa.String(length=128), nullable=False),
    sa.Column('meta_value', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['page.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('old_id', sa.Integer(), nullable=False),
    sa.Column('image_slug', sa.String(length=255), nullable=False),
    sa.Column('gallery_id', sa.Integer(), nullable=True),
    sa.Column('old_gallery_id', sa.Integer(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('caption', sa.String(length=4096), nullable=True),
    sa.Column('alt_text', sa.String(length=1024), nullable=True),
    sa.Column('image_date', sa.DateTime(), nullable=True),
    sa.Column('meta_data', sa.UnicodeText(length=4096), nullable=True),
    sa.ForeignKeyConstraint(['gallery_id'], ['photo_gallery.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photo_gallery_meta',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gallery_id', sa.Integer(), nullable=False),
    sa.Column('meta_key', sa.String(length=128), nullable=False),
    sa.Column('meta_value', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['gallery_id'], ['photo_gallery.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photo_meta',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gallery_id', sa.Integer(), nullable=False),
    sa.Column('meta_key', sa.String(length=128), nullable=False),
    sa.Column('meta_value', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['gallery_id'], ['photo_gallery.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles')
    op.drop_table('photo_meta')
    op.drop_table('photo_gallery_meta')
    op.drop_table('photo')
    op.drop_table('page_meta')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('photo_gallery')
    op.drop_table('page')
    # ### end Alembic commands ###
